### ISSUE TITLE
mistyped message

### ISSUE THREAD

**Issue by HyungJu** [JunhoYeo/Allyajyo#1]
sys.stdout.write("not a voild command\n")

->

sys.stdout.write("not a vaild command\n")

**Comment by junhoyeo** [comment]
덕분에 확인했습니다. 해당 부분을 수정하도록 하겠습니다!
다시 한번 감사드리고 앞으로도 Allyajyo 프로젝트에 꾸준한 관심 부탁드리겠습니다! 
*말씀하신 대로 `sys.stdout.write("not a vaild command\n")`로 수정될 것 같습니다 :)

**Comment by junhoyeo** [comment]
![image](https://user-images.githubusercontent.com/32605822/35914102-5d1c2e4a-0c45-11e8-9154-fc9d855c8db6.png)
위 이미지와 같이 오류를 수정하였고 곧 커밋하도록 하겠습니다.
감사의 의미에서 `Allyajyo/README.md`의 맨 하단 `Contributors` 부분에 
`@HyungJu(HyungJu) : First Issue (mistyped message)`으로 기재해 드렸습니다. 감사합니다!

**Comment by junhoyeo** [comment]
커밋하였습니다!
